### ISSUE TITLE
Doesn't see tests and fails with NullPointerException

### ISSUE THREAD

**Issue by php-coder** [gmu-swe/deflaker#1]
I'm trying to run deflaker but it fails on my project:
```console
$ mvn clean test
[INFO] Scanning for projects...
Deflaker, version 1.4 loading...
Warning: Deflaker disabling incompatible com.mycila:license-maven-plugin from mystamps
Warning: Deflaker disabling incompatible org.apache.maven.plugins:maven-enforcer-plugin from mystamps
Warning: Deflaker disabling incompatible org.jacoco:jacoco-maven-plugin from mystamps
Detected TestNG...
Detected TestNG...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building My Stamps 0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
...
[INFO] --- deflaker-maven-plugin:1.4:diff (deflaker-diff) @ mystamps ---
/home/coder/mystamps/.git DIFF'ing to HEAD
Diff'ing 13873c1f3dd81df4cf25f10ee80f4960454a3977 against: e40a2170048ce3252e02f14d0b4715dba0a40bb2
ru/mystamps/web/service/SeriesImportServiceImpl : [Edit [start=82, end=81]]
	 Methods to watch:[]
ru/mystamps/web/service/TestObjects : [Edit [start=24, end=25], Edit [start=27, end=27], Edit [start=221, end=225]]
	 Methods to watch:[]
[INFO] 
[INFO] --- deflaker-maven-plugin:1.4:diff (deflaker-diff) @ mystamps ---
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ mystamps ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 47 source files to /home/coder/mystamps/target/test-classes
[INFO] 
[INFO] --- gmavenplus-plugin:1.5:testCompile (default) @ mystamps ---
[INFO] Using Groovy 2.0.8 to perform testCompile.
[INFO] Compiled 249 files.
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ mystamps ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.007 s
[INFO] Finished at: 2017-12-15T18:27:21+01:00
[INFO] Final Memory: 78M/625M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project mystamps: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process
[ERROR] java.lang.NullPointerException
[ERROR] at java.lang.Class.forName0(Native Method)
[ERROR] at java.lang.Class.forName(Class.java:264)
[ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.getConfigurator(TestNGExecutor.java:289)
[ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:86)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
[ERROR] at org.deflaker.surefire.ReExecTestNGProvider.invoke(ReExecTestNGProvider.java:207)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] -> [Help 1]
```
The issue most likely relates to my configuration -- I have both JUnit (for unit tests) and TestNG (for integration tests) in the classpath. I configured surefire plugin to ignore TestNG:

https://github.com/php-coder/mystamps/blob/13873c1f3dd81df4cf25f10ee80f4960454a3977/pom.xml#L841-L851

How to configure deflake to also ignore TestNG?

**Comment by jon-bell** [comment]
Hi, I'm sorry - I wasn't getting notifications for this project and it fell off of my radar. If this is an issue you are still interested in please let me know and I'm sure that I can address it quickly.
