### ISSUE TITLE
Is deflaker-maven-extension:1.4 and deflaker-maven-extension:1.5-SNAPSHOT supports JDK 11

### ISSUE THREAD

**Issue by venkatrs-ch197** [gmu-swe/deflaker#7]
Hi,
I tried to use **deflaker-maven-extension:1.4** but it is giving me the below error during Maven build.
```
Deflaker, version 1.4 loading...
Warning: Deflaker disabling incompatible org.jacoco:jacoco-maven-plugin
Warning: Deflaker disabling incompatible org.apache.maven.plugins:maven-enforcer-plugin
[ERROR] Internal error: java.lang.UnsupportedOperationException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.UnsupportedOperationException
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:120)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.UnsupportedOperationException
	at java.base/java.util.Collections$UnmodifiableCollection.removeAll(Collections.java:1071)
	at org.deflaker.maven.DeflakerLifecycleParticipant.removeAnnoyingPlugins(DeflakerLifecycleParticipant.java:401)
	at org.deflaker.maven.DeflakerLifecycleParticipant.afterProjectsRead(DeflakerLifecycleParticipant.java:142)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:264)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	... 11 more
[ERROR]
```
We are using jacoco-maven-plugin version : 0.8.5 and maven-enforcer-plugin version : 3.0.0-M3

Also, I'm unable to find **deflaker-maven-extension:1.5-SNAPSHOT** in Maven repository.
I checked the pom.xml of the deflaker project from github (https://github.com/gmu-swe/deflaker/blob/master/pom.xml)

I could find that the compiler plugin is using 1.7.
```
<plugin>
        <artifactId>maven-compiler-plugin</artifactId>
	<version>3.1</version>
	<configuration>
		<source>1.7</source>
		<target>1.7</target>
	</configuration>
</plugin>
```

1. Could you please let me know will the **deflaker-maven-extension plugin** supports for **OpenJDK11**?
2. Please let me know how can I integrate **deflaker-maven-extension plugin** to our project which uses OpenJDK11?

**Comment by jon-bell** [comment]
This is not an issue with JDK 11: this is due to a breaking change inside of Maven. Please note that Java is forwards compatible: code that is compiled for Java 7 is in fact compatible with future versions of Java, too: changing that snippet to say 11 will just result in it no longer working on older code.

To use the snapshot version, you can either install it locally yourself using `mvn install`, or add the Sonatype snapshot server (https://oss.sonatype.org/content/repositories/snapshots) - note that Maven Central does not accept snapshot releases, so you generally won't be successful trying to use a snapshot version of anything in your projects if you don't add a maven repository that hosts those snapshot releases, or compile them yourself.

What happens when you use version 1.5-SNAPSHOT?

**Comment by venkatrs-ch197** [comment]
When I use 1.5-SNAPSHOT using Sonatype snapshot server  (https://oss.sonatype.org/content/repositories/snapshots), it gives me the below error
`[INFO] Scanning for projects...
[WARNING] The POM for org.deflaker:deflaker-maven-extension:jar:1.5-SNAPSHOT is missing, no dependency information available
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.deflaker:deflaker-maven-extension:1.5-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.deflaker:deflaker-maven-extension:jar:1.5-SNAPSHOT @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.deflaker:deflaker-test:0.0.1-SNAPSHOT (D:\Venkat_Personal\Personal\Programs\DeFlaker\deflaker\pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.deflaker:deflaker-maven-extension:1.5-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.deflaker:deflaker-maven-extension:jar:1.5-SNAPSHOT -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException
`

**_I've cloned the deflaker application from git (https://github.com/gmu-swe/deflaker.git) and ran mvn install. The jars are downloaded and placed into .m2 folder_**

I started maven build in eclipse and it gives me an error "**Couldn't calculate diff**"
Please find the error log.
`
java.lang.NullPointerException
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:857)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
	at org.deflaker.diff.PreciseLineAnalyzer.getChanges(PreciseLineAnalyzer.java:668)
	at org.deflaker.maven.DeflakerDiffingMojo.execute(DeflakerDiffingMojo.java:330)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)`

**Comment by jon-bell** [comment]
DeFlaker works by tracking the changes to your files in git. To use DeFlaker, your project must be in a git repository, and for the easiest use case, your git repository (.git folder) should be located in the same directory that your base `pom.xml` file is in.
